import React from "react";

export const games = [
  {
    id: 1,
    name: "Exploding Kittens",
    price: 5299,
    category: "party games",
    new_arrival: true,
    shipping: true,
    stars: 4.2,
    reviews: 61,
    image: "https://m.media-amazon.com/images/I/614u7plTGfL._AC_SL1400_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/614u7plTGfL._AC_SL1400_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71rbQKgBYKL._AC_SL1400_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71vGhvDJScL._AC_SL1400_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/718iv3fA4HL._AC_SL1400_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/712fjJPoJAL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 3,
    description:
      "Designed by prominent game developers and creators, Exploding Kittens became the most-backed Kickstarter game ever. The game is a strategic, feline spin on Russian Roulette where players draw cards until an Exploding Kitten card is pulled. This card ends the game for the player unless they have a Defuse card, which neutralizes the threat. The game set includes 56 cards, a box, and instructions. It can be played independently or with other decks for more players. Just a note, the box doesn't meow!",
    number_of_players: "2-10",
  },
  {
    id: 2,
    name: "Risk",
    price: 2399,
    category: "strategy games",
    new_arrival: false,
    shipping: false,
    stars: 4.2,
    reviews: 61,
    image: "https://m.media-amazon.com/images/I/712t+lWwFUL._AC_SX679_.jpg",
    images: [
      {
        id: "1yyy",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/712t+lWwFUL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2yyy",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/8182xDY-5kL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3yyy",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/819k2KPLaqL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4yyy",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81QV5NfQ6sL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5yyy",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81IARqKwUrL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 7,
    description:
      "Take over the world in this game of strategy conquest, now with updated figures and improved Mission cards. In the Risk game, the goal is simple: players aim to conquer their enemies territories by building an army, moving their troops in, and engaging in battle. Depending on the roll of the dice, a player will either defeat the enemy or be defeated. This exciting game is filled with betrayal, alliances, and surprise attacks. On the battlefield, anything goes! Defeat all of the enemy troops in a territory to conquer that territory and get one step closer to global conquest! The player who completes his or her secret mission first -- and reveals the Secret Mission card to prove it -- wins. And remember when it comes to taking over the world, its all about who is willing to take the biggest Risk.",
    number_of_players: "3-4",
  },
  {
    id: 3,
    name: "Monopoly",
    price: 1699,
    category: "family games",
    new_arrival: true,
    shipping: true,
    stars: 2.7,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/816dE7TY9xL._AC_SX679_.jpg",
    images: [
      {
        id: "1nnn",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/816dE7TY9xL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2nnn",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81ZbSo9bcjL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3nnn",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/812z45q0jYL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4nnn",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81X8ncu0VoL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5nnn",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71Ll2qdg8GL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 4,
    description:
      "With its classic Monopoly gameplay, this Monopoly board game is a go-to game for Family Game Night or anytime indoor fun, and it makes a great gift for families and kids. Players compete to buy out neighborhoods, sell properties, charge rent, and grow an empire in the Monopoly game for adults and kids ages 8 and up",
    number_of_players: "2-6",
  },
  {
    id: 4,
    name: "Operation Game",
    price: 1499,
    category: "electrified games",
    new_arrival: true,
    shipping: false,
    stars: 5.0,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/81XzqHpzQXL._AC_SX679_.jpg",
    images: [
      {
        id: "1ccc",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81XzqHpzQXL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2ccc",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81jXoBo+sPL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3ccc",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81tEKdrRXkL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4ccc",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81LdA2GJ7TL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5ccc",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71nBbE2szDL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 2,
    description:
      "It's a classic family favourite! Cavity Sam is feeling a little under the weather. Kids will love to 'operate' and make him feel better. As soon as they grab the tweezers, get ready for giggles as they attempt to remove Sam's anatomy parts without getting buzzed!",
    number_of_players: "1",
  },

  {
    id: 5,
    name: "Catan",
    price: 1234,
    category: "modern classic",
    new_arrival: false,
    shipping: true,
    stars: 3.5,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/812ZMYDeGZL._AC_SX679_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/812ZMYDeGZL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/91P396ws4PL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/818oIpXL7tL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81+okm4IpfL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81rSEZZBGzL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 3,
    description:
      "Set off on a quest to settle the isle of Catan. Guide your settlers to victory by smart trading and cunning development. Use resource combinations to buy useful development cards and build roads, settlements, and cities. Come by your resources through trades, cards, or lucky dice. But watch out! Someone may cut off your road and you never know when the robber might steal some of your needed gains!",
    number_of_players: "3-4",
  },

  {
    id: 6,
    name: "Clue",
    price: 3499,
    category: "mystery games",
    new_arrival: true,
    shipping: true,
    stars: 2.1,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/71oSGWDuUgL._AC_SL1500_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71oSGWDuUgL._AC_SL1500_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81+rvJE79gL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71kMcfg6dSL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/71aKDJVWWfL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81sYnh9mgCL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 2,
    description:
      "This version of Clue elevates the classic murder mystery game with a fresh take on the original plot, characters, and elegant Tudor Mansion. Players must solve Boddy Black's murder by gathering clues and racing to uncover the murderer, location, and weapon. Play as one of six suspects, each with unique backstories and secrets. The game boasts premium components including gold-plated weapon tokens, sculpted character movers, and detailed illustrations. Clue cards speed up the investigation by revealing hints. Suitable for family game nights, this immersive mystery game is designed for ages 8 and up.",
    number_of_players: "2-6",
  },

  {
    id: 7,
    name: "The Game of Life",
    price: 999,
    category: "family games",
    new_arrival: false,
    shipping: false,
    stars: 4.5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/81A0K5YsuxL._AC_SX679_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81A0K5YsuxL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81E9Qgk085L._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81WIGQDL9dL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/91P4YBAHddL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/91D8rzZBtYL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 3,
    description:
      "This board game features 6 vibrant peg colors to represent players as they navigate around the gameboard. In this engaging family game, each crossroad offers thrilling choices and adventures. Players make important life decisions, like attending college, marriage, expanding the family, or early retirement. Opportunities to invest in board numbers can lead to monetary growth whenever that number is spun. The Game of Life is an enjoyable activity for 2-4 players, suitable for parties, game nights, or homeschooling. It's an indoor fun option for kids aged 8 and above.",
    number_of_players: "2-4",
  },

  {
    id: 8,
    name: "Scrabble",
    price: 2599,
    category: "modern classic",
    new_arrival: false,
    shipping: true,
    stars: 4.1,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/51O+I4BU2PL._AC_SX679_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/51O+I4BU2PL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/61CLhsNdQgL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/61pRXhbi1oL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/610yvtGe2JL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/61ROCuzWL5L._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 5,
    description:
      "Scrabble, the classic crossword game, is a perfect choice for a fun family game night. This edition features wooden letter tiles, racks, and a textured gameboard that securely holds the tiles. Points are earned by constructing words with letter tiles, with premium squares offering score multipliers. Deploy 2-letter words to surprise opponents, challenge their choices, and strategize for the win. Suitable for 2-4 players, Scrabble can be played in teams or as classic one-on-one matches. The game guide provides expert tips and alternate gameplays. Introduce your kids and grandkids to this timeless word game and create lasting memories.",
    number_of_players: "2-4",
  },

  {
    id: 9,
    name: "Candy Land",
    price: 2999,
    category: "family games",
    new_arrival: false,
    shipping: false,
    stars: 3.3,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/91yUG40gv0L._AC_SX679_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/91yUG40gv0L._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/91Epa2nkxUL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81WvpYI+mkL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81DKf6bML+L._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/81-G2FuTlkL._AC_SX679_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 10,
    description:
      "Candy Land is a timeless board game that allows new generations to enjoy its sweetness. Players advance their delightful gingerbread man pawn on the path, racing towards the castle while encountering a variety of 'tasty' surprises. The game, designed for children ages 3 and up, requires no reading, making it an excellent choice for pre-readers. Candy Land captivates young players with its vibrant cards, enchanting destinations, and engaging illustrations. This sweet reinterpretation of the classic board game includes a gameboard, four pawns, a deck of cards, and instructions.",
    number_of_players: "2-4",
  },

  {
    id: 10,
    name: "Deadly Dowagers",
    price: 3599,
    category: "strategy games",
    new_arrival: false,
    shipping: false,
    stars: 5.0,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/5197DyesvLL._AC_.jpg",
    images: [
      {
        id: "1xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/5197DyesvLL._AC_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "2xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/51Xvtd8QfhL._AC_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "3xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/414D+7xBeML._AC_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "4xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/517IsNbOrcL._AC_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
      {
        id: "5xxx",
        width: 1000,
        height: 667,
        url: "https://m.media-amazon.com/images/I/51HR8YRH+6L._AC_.jpg",
        filename: "81+okm4IpfL._AC_SX679_.jpg",
        type: "image/jpeg",
      },
    ],
    stock: 1,
    description:
      "Deadly Dowagers is a strategic card-drafting game where players compete to increase their dowries while managing their reputations. The goal is to accumulate wealth by tactfully marrying and then eliminating husbands without garnering excessive notoriety, which might deter potential noble suitors. The game cleverly intertwines themes of marriage, wealth, and intrigue, all presented with stunning artwork and stylish design.",
    number_of_players: "2-6",
  },
];
